
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import BOTH, YES, Image, Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
from tkinter.tix import IMAGETEXT





OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1196x794")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 794,
    width = 1196,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1196.0,
    794.0,
    fill="#33ccff",
    outline="")

canvas.create_rectangle(
    193.0,
    79.0,
    1004.0,
    714.0,
    fill="#0082C8",
    outline="")

# def resize_image(event):
#     new_width = event.width
#     new_height = event.height
#     image = copy_of_image.resize((new_width, new_height))
#     photo = IMAGETEXT.PhotoImage(image)
#     label.config(image = photo)
#     label.image = photo #avoid garbage collection


# from tkinter import *
# from tkinter import ttk
# from PIL import Image, ImageTk

# image = Image.open('image_1.png')
# copy_of_image = image.copy()
# photo = ImageTk.PhotoImage(image)
# label = ttk.Label(window, image = photo)
# label.bind('<Configure>', resize_image)
# label.pack(fill=BOTH, expand = YES)

# window.mainloop()

# entry_image_1 = PhotoImage(
#     file=relative_to_assets("image_1.png"))
# entry_bg_1 = canvas.create_image(
#     810.0,
#     267.5,
#     image=entry_image_1
# )
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=657.0,
    y=212.0,
    width=238.0,
    height=29.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=657.0,
    y=141.0,
    width=245.0,
    height=39.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    801.0,
    638.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_2.place(
    x=682.0,
    y=623.0,
    width=238.0,
    height=29.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    357.0,
    236.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_3.place(
    x=238.0,
    y=221.0,
    width=238.0,
    height=29.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=239.0,
    y=363.0,
    width=167.0,
    height=33.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=238.0,
    y=146.0,
    width=127.0,
    height=33.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,

    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=682.0,
    y=525.0,
    width=200.0,
    height=50.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    357.0,
    463.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_4.place(
    x=238.0,
    y=448.0,
    width=238.0,
    height=29.0
)
vlist = ["IDF", "TF", "FULL"]
 
Combo = ttk.Combobox(window, values = vlist, state="readonly")
Combo.set("Pick an Option")
Combo.place(
    x=715.0,
    y=264.0,
    width=99.0,
    height=18.0
)

vlist = ["Cosine Measure", "PCC measure"]
 
Combo = ttk.Combobox(window, values = vlist, state="readonly")
Combo.set("Pick an Option")
Combo.place(
    x=715.0,
    y=354.0,
    width=99.0,
    height=18.0
)
vlist = ["Indexing", "Non indexing"]
 
Combo = ttk.Combobox(window, values = vlist, state="readonly")
Combo.set("Pick an Option")
Combo.place(
    x=715.0,
    y=444.0,
    width=99.0,
    height=18.0
)

Combo.config(font='Aerial 7',justify='center'  )
Combo.config(font='Aerial 7',justify='center'  )
Combo.config(font='Aerial 7',justify='center'  )

window.resizable(False, False)
window.mainloop()
